#!/usr/bin/python
#
#  viabmon-cgi - Vacmon CGI script
#
#  Andrew McNab, University of Manchester.
#  Copyright (c) 2015-6. All rights reserved.
#
#  Redistribution and use in source and binary forms, with or
#  without modification, are permitted provided that the following
#  conditions are met:
#
#    o Redistributions of source code must retain the above
#      copyright notice, this list of conditions and the following
#      disclaimer. 
#    o Redistributions in binary form must reproduce the above
#      copyright notice, this list of conditions and the following
#      disclaimer in the documentation and/or other materials
#      provided with the distribution. 
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND
#  CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
#  INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
#  DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS
#  BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
#  EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
#  TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
#  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
#  ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
#  OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
#  OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#  POSSIBILITY OF SUCH DAMAGE.
#
#  Contacts: Andrew.McNab@cern.ch  http://www.gridpp.ac.uk/vacproject/
#

import os
import cgi
import string
import pprint
import elasticsearch

# ##Unused from viab?
import re
import sys
import stat
import time
import shutil
import hashlib
import tempfile
import inspect
import textwrap
# ###

def htmlHeader(title):
  print 'Content-Type: text/html'
  print
  print '<html><head><title>' + title + '</title>'
  print open('/var/www/vacmon/header.html', 'r').read()

def htmlFooter():
  print open('/var/www/vacmon/footer.html', 'r').read()
  print '</html>'

def oneFactory(timeRange, voName, siteName, spaceName, factoryName):
            
  htmlHeader('Vacmon')

  es = elasticsearch.Elasticsearch()
  
  t = es.search(
          index    = 'vacmon',
          doc_type = 'factories',
          size     = 0,
          body =  """{
            "query": 
              {
                filtered:
                 {
                   "filter": 
                     { 
                       "match": 
                         { 
                           "factory": "vac-79.hep.manchester.ac.uk"
                         },
                         {
                           "range": 
                             {
                               "time_sent": 
                                 {
                                   "gt" : 0,
                                   "lt" : 1582050315
                                 }
                             }
                         }
                     }
                 },                          
            "aggs" : 
              {
                "perfac1": 
                  {
                    "date_histogram": 
                      { 
                        "field"    : "time_sent",
                        "interval" : "1000s",
                        "format"   : "epoch_second"
                      },
                    "aggs": 
                      {
                        "perfac2": 
                          {
                            "avg": 
                              {
                                "field": "load_average" 
                              }
                          }
                      }
                  }
              }                         
           }"""
         )

  pprint.pprint(t)

  htmlFooter()
  
#
# PROGRAM MAIN
#

# URIs are like: /timerange[:VO]/[sitename/[spacename/[factory/]]]

vacmonVersion = open('/var/www/vacmon/VERSION','r').readline().split('=',1)[1].strip()
requestURI    = os.environ['REQUEST_URI']

if '..' in requestURI or string.translate(requestURI, None, '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ_-./') != '':
  # Redirect to main page if unacceptable characters in URI
  print 'Status: 302 Found'
  print 'Location: http://vacmon.gridpp.ac.uk/vacmon/'
  print
  sys.exit(0)

timeRangeVO, siteName, spaceName, factoryName = (requestURI + '////').split('/')[1:5]

if ':' in timeRangeVO:
  timeRange = timeRangeVO.split(':')[0]
  voName    = timeRangeVO.split(':')[1]
else:
  timeRange = timeRangeVO
  voName    = None

# Static pages: main page and documentation

if not timeRangeVO:
  htmlHeader('Vacmon')

  try:
    print open('/var/www/vacmon/index.html', 'r').read()
  except:
    pass  

  htmlFooter(userDN)
  sys.exit(0)

# Pages with graphs

if siteName and spaceName and factoryName:
  oneFactory(timeRange, voName, siteName, spaceName, factoryName)

sys.exit(0)
